sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 085258
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: sky-itcast-ppx
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: 
    secret: 
    mchid: 1561414331
    mchSerialNo: 
    privateKeyFilePath: 
    apiV3Key: 
    weChatPayCertFilePath: 
    notifyUrl: https://424fdaa2.r15.vip.cpolar.cn/wxpay/pay.php
    refundNotifyUrl: https://424fdaa2.r15.vip.cpolar.cn/wxpay/pay.php
