sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 085258
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQFHSjHVC7RRsJ6iMBh
    access-key-secret: 6E9N6ST4YYqONTjHcpd1QAUXcXN258
    bucket-name: sky-itcast-ppx