sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 085258
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQFHSjHVC7RRsJ6iMBh
    access-key-secret: 6E9N6ST4YYqONTjHcpd1QAUXcXN258
    bucket-name: sky-itcast-ppx
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxb1d9b133b555cc9a
    secret: 6e4c4e9a9250f0b7054871e548062fda
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://424fdaa2.r15.vip.cpolar.cn/wxpay/pay.php
    refundNotifyUrl: https://424fdaa2.r15.vip.cpolar.cn/wxpay/pay.php